service: oc-headless-site-frontend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1 
functions:
  edgeFunction:
    handler: edgeHandler.edge
    events:
      - http:
          path: /
          method: ANY

package:
  individually: true
  exclude:
    - node_modules/**
    - .next/cache/**
    - .git/**
    - .github/**
    - tests/**
    - .eslint*
    - .prettier*
    - '**/*.md'