export const cancerTypesPerRegionMock = [
  { id: 1, name: "Bexiga", regionId: 3 },
  { id: 2, name: "Boca", regionId: 4 },
  { id: 3, name: "Câncer Anal", regionId: 3 },
  { id: 4, name: "Câncer de Colo de Útero", regionId: 3 },
  { id: 5, name: "Câncer de Fígado", regionId: 2 },
  { id: 6, name: "Câncer de Mama", regionId: 7 },
  { id: 7, name: "Câncer de Ouvido", regionId: 4 },
  { id: 8, name: "Câncer de Pâncreas", regionId: 2 },
  { id: 9, name: "Câncer de Sistema Nervoso Central", regionId: 4 },
  { id: 10, name: "Câncer de Timo", regionId: 7 },
  { id: 11, name: "Câncer Infantiljuvenil", regionId: 5 },
  { id: 12, name: "Câncer Uretral", regionId: 3 },
  { id: 13, name: "Carcinoma de Merkel", regionId: 4 },
  { id: 14, name: "Cavidade Nasal e Seios Paranasais", regionId: 4 },
  { id: 15, name: "Colorretal", regionId: 3 },
  { id: 16, name: "Corpo de Útero - Endométrio", regionId: 3 },
  { id: 17, name: "Doença de Castleman", regionId: 5 },
  { id: 18, name: "Doença de Paget", regionId: 6 },
  { id: 19, name: "Esôfago", regionId: 6 },
  { id: 20, name: "Estômago", regionId: 2 },
  { id: 21, name: "Garganta", regionId: 6 },
  { id: 22, name: "Glândulas Salivares", regionId: 4 },
  { id: 23, name: "Glioblastoma", regionId: 4 },
  { id: 24, name: "Hepatoblastoma", regionId: 2 },
  { id: 25, name: "Intestino Delgado", regionId: 3 },
  { id: 26, name: "Laringe", regionId: 6 },
  { id: 27, name: "Leucemia", regionId: 5 },
  { id: 28, name: "Leucemia em Crianças", regionId: 5 },
  { id: 29, name: "Linfoma de Hodgkin", regionId: 5 },
  { id: 30, name: "Linfoma em Crianças", regionId: 5 },
  { id: 31, name: "Linfoma Não Hodgkin", regionId: 5 },
  { id: 32, name: "Mama em Homens", regionId: 7 },
  { id: 33, name: "Melanoma", regionId: 5 },
  { id: 34, name: "Melanoma Ocular", regionId: 4 },
  { id: 35, name: "Meningioma", regionId: 4 },
  { id: 36, name: "Mesotelioma", regionId: 7 },
  { id: 37, name: "Metástase", regionId: 5 },
  { id: 38, name: "Mielofibrose", regionId: 5 },
  { id: 39, name: "Mieloma Múltiplo", regionId: 5 },
  { id: 40, name: "Nasofaringe", regionId: 4 },
  { id: 41, name: "Neoplasia de Baço", regionId: 2 },
  { id: 42, name: "Neuroblastoma", regionId: 5 },
  { id: 43, name: "Olho - Retinoblastoma", regionId: 4 },
  { id: 44, name: "Ovário", regionId: 3 },
  { id: 45, name: "Paratireoide", regionId: 6 },
  { id: 46, name: "Pele Não Melanoma", regionId: 5 },
  { id: 47, name: "Pênis", regionId: 3 },
  { id: 48, name: "Peritônio", regionId: 2 },
  { id: 49, name: "Pituitários / da Hipófise", regionId: 4 },
  { id: 50, name: "Próstata", regionId: 3 },
  { id: 51, name: "Pulmão", regionId: 7 },
  { id: 52, name: "Rim", regionId: 3 },
  { id: 53, name: "Sarcoma de Ewing", regionId: 5 },
  { id: 54, name: "Sarcomas de Partes Moles", regionId: 5 },
  { id: 55, name: "Sarcomas Ósseos", regionId: 5 },
  { id: 56, name: "Síndrome de Li-Fraumeni", regionId: 5 },
  { id: 57, name: "Síndrome de Lynch", regionId: 5 },
  { id: 58, name: "Síndrome Mielodisplásica", regionId: 5 },
  { id: 59, name: "Sítio Primário Desconhecido", regionId: 5 },
  { id: 60, name: "Testículo", regionId: 3 },
  { id: 61, name: "Tireóide", regionId: 6 },
  { id: 62, name: "Traqueia", regionId: 6 },
  { id: 63, name: "Trompa de Falópio", regionId: 3 },
  { id: 64, name: "Tumor Cardíaco", regionId: 7 },
  { id: 65, name: "Tumor de Wilms", regionId: 5 },
  { id: 66, name: "Tumores Adrenais ou Suprarrenais", regionId: 2 },
  { id: 67, name: "Tumores da Medula Espinhal", regionId: 4 },
  { id: 68, name: "Tumores Neuroendocrinos", regionId: 5 },
  { id: 69, name: "Vesícula Biliar", regionId: 2 },
];
