export const glossaryData = [
  {
    id: 1,
    letter: "A",
    terms: [
      "Adenocarcinoma",
      "Adenomegalia",
      "Adjuvante Alfa-Fetoproteína (AFP)",
      "Alopecia",
      "Anamnese",
      "Anaplasia Anatomopatológico",
      "Anemia",
      "Angiogênese",
      "Anticorpo Monoclonal",
      "Antígeno Carcinoembrionário (CEA)",
      "Apoptose Astrocitoma",
    ],
  },
  {
    id: 2,
    letter: "B",
    terms: [
      "Bastonetes",
      "Beta-2-Microglobulin",
      "Beta-HCG",
      "Bilirrubina",
      "Biópsia",
      "Bisfosfonato(s)",
      "Braquiterapia",
    ],
  },
  {
    id: 3,
    letter: "C",
    terms: [
      "CA 15-3",
      "CA 19-9",
      "Carcinogênico",
      "Carcinoma",
      "Carcinoma de Pequenas Células",
      "Carcinoma Epidermóide Cariótipo",
      "Cerebelo",
      "Cérebro",
      "Ciclo de Tratamento",
      "Cintilografia Óssea Cirurgia",
      "Conservadora",
      "Citogenética",
      "Creatinina",
      "Cromossomo(s)",
      "Cuidados Paliativos Cura",
    ],
  },
  {
    id: 4,
    letter: "D",
    terms: [
      "CA 15-3",
      "CA 19-9",
      "Carcinogênico",
      "Carcinoma",
      "Carcinoma de Pequenas Células",
      "Carcinoma Epidermóide Cariótipo",
      "Cerebelo",
      "Cérebro",
      "Ciclo de Tratamento",
      "Cintilografia Óssea Cirurgia",
      "Conservadora",
      "Citogenética",
      "Creatinina",
      "Cromossomo(s)",
      "Cuidados Paliativos Cura",
    ],
  },
  {
    id: 5,
    letter: "E",
    terms: [
      "CA 15-3",
      "CA 19-9",
      "Carcinogênico",
      "Carcinoma",
      "Carcinoma de Pequenas Células",
      "Carcinoma Epidermóide Cariótipo",
      "Cerebelo",
      "Cérebro",
      "Ciclo de Tratamento",
      "Cintilografia Óssea Cirurgia",
      "Conservadora",
      "Citogenética",
      "Creatinina",
      "Cromossomo(s)",
      "Cuidados Paliativos Cura",
    ],
  },
  {
    id: 6,
    letter: "F",
    terms: [
      "CA 15-3",
      "CA 19-9",
      "Carcinogênico",
      "Carcinoma",
      "Carcinoma de Pequenas Células",
      "Carcinoma Epidermóide Cariótipo",
      "Cerebelo",
      "Cérebro",
      "Ciclo de Tratamento",
      "Cintilografia Óssea Cirurgia",
      "Conservadora",
      "Citogenética",
      "Creatinina",
      "Cromossomo(s)",
      "Cuidados Paliativos Cura",
    ],
  },
];
