export const unitsData = [
  {
    unitName: "Oc Faria Lima",
    address: "Avenida Brigadeiro Faria Lima, 4.300",
    complement: "6º e 10º Andar - Vila Olímpia",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    specialties: [
      "Cardiologia oncológica",
      "Dermatologia",
      "Genética médica",
      "Hematologia",
      "Medicina paliativa",
      "Oncologia clínica",
    ],
  },
  {
    unitName: "Oc Precision Medicine",
    address: "Rua Natividade, 139",
    complement: "Vila Nova Conceição",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    specialties: ["Anatomia Patológica", "Genômica"],
  },
  {
    unitName: "Oc Higienópolis",
    address: "Rua Mato Grosso, 306",
    complement: "2º e 8º Andar - Higienópolis",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    specialties: [
      "Cardiologia oncológica",
      "Dermatologia",
      "Genética médica",
      "Hematologia",
      "Medicina paliativa",
      "Oncologia clínica",
    ],
  },
];
