mutation CreatePost($createPostInput: CreatePostInput!) {
  createPost(createPostInput: $createPostInput) {
    id
    title
    content
    published
    userId
    createdAt
  }
}

mutation RemovePost($removePostId: String!) {
  removePost(id: $removePostId) {
    id
    title
    content
    published
    userId
    createdAt
  }
}

mutation UpdatePost($updatePostInput: UpdatePostInput!) {
  updatePost(updatePostInput: $updatePostInput) {
    id
    title
    content
    published
    userId
    createdAt
  }
}
