mutation CreateUser($createUserInput: CreateUserInput!) {
  createUser(createUserInput: $createUserInput) {
    id
    email
    name
    posts {
      id
      title
      content
      published
      userId
      createdAt
    }
    createdAt
  }
}

mutation RemoveUser($removeUserId: String!) {
  removeUser(id: $removeUserId) {
    id
    email
    name
    posts {
      id
      title
      content
      published
      userId
      createdAt
    }
    createdAt
  }
}

mutation UpdateUser($updateUserInput: UpdateUserInput!) {
  updateUser(updateUserInput: $updateUserInput) {
    id
    email
    name
    posts {
      id
      title
      content
      published
      userId
      createdAt
    }
    createdAt
  }
}
