export const alphabetMock = [
  { key: 1, value: "A", label: "A" },
  { key: 2, value: "B", label: "B" },
  { key: 3, value: "C", label: "C" },
  { key: 4, value: "D", label: "D" },
  { key: 5, value: "E", label: "E" },
  { key: 6, value: "F", label: "F" },
  { key: 7, value: "G", label: "G" },
  { key: 8, value: "H", label: "H" },
  { key: 9, value: "I", label: "I" },
  { key: 10, value: "J", label: "J" },
  { key: 11, value: "K", label: "K" },
  { key: 12, value: "L", label: "L" },
  { key: 13, value: "M", label: "M" },
  { key: 14, value: "N", label: "N" },
  { key: 15, value: "O", label: "O" },
  { key: 16, value: "P", label: "P" },
  { key: 17, value: "Q", label: "Q" },
  { key: 18, value: "R", label: "R" },
  { key: 19, value: "S", label: "S" },
  { key: 20, value: "T", label: "T" },
  { key: 21, value: "U", label: "U" },
  { key: 22, value: "V", label: "V" },
  { key: 23, value: "W", label: "W" },
  { key: 24, value: "X", label: "X" },
  { key: 25, value: "Y", label: "Y" },
  { key: 26, value: "Z", label: "Z" },
];
