const unitiesInformation = [
  {
    id: 1,
    state: "Paraná",
    title: "PR - UNIDADE: OC ONCOCLÍNICAS LONDRINA | PRO ONCO",
    address:
      "Av. Adhemar Pereira de Barros, 679 - Jardim Bela Suíça. Londrina - PR",
    availableVaccines: [
      "HIB (Haemophilus Influenzae B)",
      "HPV Quadrivalente Gardasil",
      "Hepatite A Adulto Dose Única",
      "Hepatite A + B Adulto",
      "Hepatite B Adulto Dose Única",
      "Herpes Zoster Inativada (Shingrix) Dose Única",
      "Influenza Quadrivalente Dose Única",
      "Menigite Conjugada B Und",
      "Meningite Acwy Und",
      "Mmr Ii Triviral(Sarampo + Caxumba + Rubeola) Und",
      "Pneumococcica 23(Pneumovax)",
      "Pneumococoica 13(Prevenar) Und",
      "Refortrix Dtpa Sem Polio Dose Und",
    ],
  },
  {
    id: 2,
    state: "Rio de Janeiro",
    title: "RIO DE JANEIRO - UNIDADE: OC ONCOCLÍNICAS BARRA DA TIJUCA",
    address: "Av. das Américas, 4000 - Barra da Tijuca. Rio de Janeiro - RJ",
    availableVaccines: [
      "BCG (Bacillus Calmette-Guerin)",
      "DTP (Difteria, Tétano, Pertussis)",
      "HPV Quadrivalente Gardasil",
      "Hepatite B Infantil",
      "Influenza Quadrivalente Dose Única",
      "Hepatite A + B Adulto",
      "Meningocócica ACWY",
    ],
  },
  {
    id: 3,
    state: "Rio Grande do Sul",
    title: "RIO GRANDE DO SUL - UNIDADE: OC ONCOCLÍNICAS PORTO ALEGRE",
    address: "Rua dos Andradas, 1474 - Centro. Porto Alegre - RS",
    availableVaccines: [
      "DTP (Difteria, Tétano, Pertussis)",
      "Hepatite A + B Adulto",
      "Hepatite B Infantil",
      "HPV Quadrivalente Gardasil",
      "Herpes Zoster Inativada (Shingrix) Dose Única",
      "Meningocócica B",
      "Influenza Quadrivalente Dose Única",
    ],
  },
  {
    id: 4,
    state: "Sergipe",
    title: "SERGIPE - UNIDADE: OC ONCOCLÍNICAS ARACAJU",
    address:
      "Avenida Presidente Tancredo Neves, 2020 - Bairro São José. Aracaju - SE",
    availableVaccines: [
      "BCG (Bacillus Calmette-Guerin)",
      "DTP (Difteria, Tétano, Pertussis)",
      "Hepatite A + B Adulto",
      "Hepatite B Infantil",
      "HPV Quadrivalente Gardasil",
      "Influenza Quadrivalente Dose Única",
      "Meningocócica C",
    ],
  },
  {
    id: 5,
    state: "São Paulo",
    title: "SÃO PAULO - UNIDADE: OC ONCOCLÍNICAS SÃO PAULO",
    address: "Avenida Paulista, 2200 - Bela Vista. São Paulo - SP",
    availableVaccines: [
      "BCG (Bacillus Calmette-Guerin)",
      "Hepatite A + B Adulto",
      "HPV Quadrivalente Gardasil",
      "DTP (Difteria, Tétano, Pertussis)",
      "Hepatite B Infantil",
      "Herpes Zoster Inativada (Shingrix) Dose Única",
      "Influenza Quadrivalente Dose Única",
    ],
  },
];

export default unitiesInformation;
