export const unitsData = [
  {
    id: 1,
    unitName: "Oc Faria Lima",
    address: "Avenida Brigadeiro Faria Lima, 4.300",
    complement: "6º e 10º Andar - Vila Olímpia",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: true,
    specialties: [
      "Cardiologia oncológica",
      "Dermatologia",
      "Genética Médica",
      "Hematologia",
      "Medicina paliativa",
      "Oncologia clínica",
    ],
  },
  {
    id: 2,
    unitName: "Oc Precision Medicine",
    address: "Rua Natividade, 139",
    complement: "Vila Nova Conceição",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: false,
    specialties: ["Anatomia Patológica", "Genômica"],
  },
  {
    id: 3,
    unitName: "Oc Higienópolis",
    address: "Rua Mato Grosso, 306",
    complement: "2º e 8º Andar - Higienópolis",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: false,
    specialties: [
      "Cardiologia oncológica",
      "Dermatologia",
      "Genética Médica",
      "Hematologia",
      "Medicina paliativa",
      "Oncologia clínica",
    ],
  },
  {
    id: 4,
    unitName: "Oc Morumbi",
    address: "Avenida Giovanni Gronchi, 5930",
    complement: "Morumbi",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: false,
    specialties: ["Oncologia clínica", "Radioterapia"],
  },
  {
    id: 5,
    unitName: "Oc Vila Mariana",
    address: "Rua Domingos de Morais, 348",
    complement: "Vila Mariana",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: false,
    specialties: ["Hematologia", "Medicina paliativa"],
  },
  {
    id: 6,
    unitName: "Oc Paulista",
    address: "Avenida Paulista, 1009",
    complement: "Bela Vista",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: false,
    specialties: ["Cardiologia oncológica", "Dermatologia"],
  },
  {
    id: 7,
    unitName: "Oc Pinheiros",
    address: "Rua dos Pinheiros, 1256",
    complement: "Pinheiros",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: true,
    specialties: ["Genética Médica", "Oncologia clínica"],
  },
  {
    id: 8,
    unitName: "Oc Ibirapuera",
    address: "Avenida Ibirapuera, 2332",
    complement: "Moema",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: true,
    specialties: ["Medicina paliativa", "Radioterapia"],
  },
  {
    id: 9,
    unitName: "Oc Tatuapé",
    address: "Rua Tuiuti, 1234",
    complement: "Tatuapé",
    city: "São Paulo - SP",
    hours: "Segunda a sexta-feira das 08:00 às 18:00",
    isPartner: false,
    specialties: ["Dermatologia", "Hematologia"],
  },
];
